# baseURL = 'https://verlindedb.github.io/'
baseURL = '/'
languageCode = 'en-us'
title = 'VerlindeDB'
theme = 'hugo-dead-simple'


[markup.goldmark.renderer]
  unsafe = true                # Allows HTML if needed
[markup.goldmark.extensions]
  typographer = false # Prevents (c) becoming Â© which breaks math
